# Generated by Django 3.1.2 on 2021-01-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attachments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachments',
            new_name='Attachment',
        ),
    ]
