# Generated by Django 3.0.8 on 2020-08-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_post_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
